= OCP4 Certificates Configuration
Francesco Minafra <francesco.minafra@redhat.com>
:revnumber: {lastcommitid}
:revdate: {lastcommitdate}
:data-uri:
:toc: left
:source-highlighter: rouge
:icons: font
:stylesdir: ../stylesheets
:stylesheet: colony.css
// :stylesheet: asciidoctor.css

:sectnums:

== Introduction

In this section we would like to discuss how to manage certificates that are
used to encrypt connections to the various components (both infrastructure and
  applications) of an OpenShift 4 cluster.

The official documentation provides the first source of information about this subject:

* https://docs.openshift.com/container-platform/4.2/networking/routes/secured-routes.html[Secured routes: re-encrypt and edge]
* https://docs.openshift.com/container-platform/4.2/authentication/certificates/replacing-default-ingress-certificate.html[Replacing the default ingress certificate]
* https://docs.openshift.com/container-platform/4.2/authentication/certificates/api-server.html[Adding API server certificates]

There are additional sources which provide more detailed descriptions on how to
perform manually the configurations. One such reference is the blog post:

* https://blog.openshift.com/requesting-and-installing-lets-encrypt-certificates-for-openshift-4/[Requesting and installing Let's Encrypt Certificates for OpenShift 4]

We should separate certificate management discussion considering that:

* A dedicated certificate is used for securing access to the API endpoint
* A Wildcard domain certificate is used for securing access to routes that do not
make use of dedicated application-specific certificates
* Individual applications may use specific certificates different from the wildcard one
* Normally the web console, the OAuth server and the dashboards for
Monitoring/Logging make use of routes that are created by OpenShift using the
wildcard DNS entry pointing to the ingress load balancer. These routes are then
normally secured using the wildcard domain certificate assigned to the default
ingress controller. Using dedicated certificates for the single components is
currently not supported

[CAUTION]
====
It may happen that the IT staff of the organization adopting OCP doesn't allow
the creation of a wildcard certificate used to serve all the routes for
applications that are not yet deployed. This may be considered a security issue,
and therefore only the API certificate may be issued by the organization CA.
This practice may lead to errors while authenticating to the API endpoint, because
during the authentication also the OAuth server is involved. Normally the OAuth
server makes use of the wildcard domain certificate assigned to the default ingress
controller. Unless the OAuth server is also configured with a valid trusted
certificate, users will get errors during the login to the API server.
====

== Assumptions

In order to demonstrate with examples how to perform the certificate-related
configurations, we will assume that:

* A cluster installed with https://docs.openshift.com/container-platform/4.2/welcome/index.html[OCP 4.2] is available
and the reader has `cluster-admin` access credentials.
** Access to the cluster will be done using both a bastion host with the `oc` client
binary installed and via the web console
** For the purpose of our demonstration, an https://docs.openshift.com/container-platform/4.2/installing/installing_aws/installing-aws-default.html[OCP4 cluster installed on AWS] will be used
* A sample application (an nginx web server) is deployed to demonstrate the
per-application configuration of secure routes.
* The availability of commercial *SSL* certificates is simulated using the freely
available certificates issued by https://letsencrypt.org/[Let's Encrypt]

== Deploying sample application
